using GrindAtlas.API.Data;
using GrindAtlas.API.Models;
using GrindAtlas.API.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using System.Text;
using System.Threading.RateLimiting;

var builder = WebApplication.CreateBuilder(args);

var dbHost     = Environment.GetEnvironmentVariable("DB_HOST")     ?? throw new InvalidOperationException("DB_HOST env var is not set");
var dbPassword = Environment.GetEnvironmentVariable("DB_PASSWORD") ?? throw new InvalidOperationException("DB_PASSWORD env var is not set");
var dbName     = Environment.GetEnvironmentVariable("DB_NAME") ?? "neondb";
var dbUser     = Environment.GetEnvironmentVariable("DB_USER") ?? "neondb_owner";
var connStr    = $"Host={dbHost};Database={dbName};Username={dbUser};Password={dbPassword};SSL Mode=Require";

builder.Services.AddDbContext<AppDbContext>(opt => opt.UseNpgsql(connStr));

builder.Services.AddIdentity<ApplicationUser, IdentityRole>(opt =>
{
    opt.Password.RequireDigit = false;
    opt.Password.RequiredLength = 6;
    opt.Password.RequireNonAlphanumeric = false;
    opt.Password.RequireUppercase = false;
})
.AddEntityFrameworkStores<AppDbContext>()
.AddDefaultTokenProviders();

var jwtKey = builder.Configuration["Jwt:Key"]!;
builder.Services.AddAuthentication(opt =>
{
    opt.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    opt.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(opt =>
{
    opt.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = builder.Configuration["Jwt:Issuer"],
        ValidAudience = builder.Configuration["Jwt:Audience"],
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)),
    };
});

builder.Services.AddAuthorization(opt =>
    opt.FallbackPolicy = new Microsoft.AspNetCore.Authorization.AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build());
builder.Services.AddScoped<GrindEstimatorService>();
builder.Services.AddScoped<IAuditLogService, AuditLogService>();

// Rate limiter — "sensitive" policy for password resets, email sends, etc.
builder.Services.AddRateLimiter(opt =>
{
    opt.AddSlidingWindowLimiter("sensitive", limiterOpt =>
    {
        limiterOpt.Window            = TimeSpan.FromHours(1);
        limiterOpt.SegmentsPerWindow = 6;
        limiterOpt.PermitLimit       = 5;
        limiterOpt.QueueLimit        = 0;
        limiterOpt.QueueProcessingOrder = QueueProcessingOrder.OldestFirst;
    });
    opt.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
});
builder.Services.Configure<EmailSettings>(builder.Configuration.GetSection("EmailSettings"));
builder.Services.AddScoped<IEmailService, SmtpEmailService>();
builder.Services.AddControllers()
    .AddJsonOptions(o =>
    {
        o.JsonSerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
        o.JsonSerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
    });

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(opt =>
{
    opt.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        In = ParameterLocation.Header,
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        Description = "Enter your JWT token. Example: eyJhbGci..."
    });
    opt.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
            },
            Array.Empty<string>()
        }
    });
});

builder.Services.AddCors(opt => opt.AddDefaultPolicy(p =>
    p.WithOrigins("http://localhost:4200", "https://grindatlas.netlify.app")
     .AllowAnyHeader()
     .AllowAnyMethod()));

var app = builder.Build();

// Initialize schema and seed data
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    db.Database.EnsureCreated();

    // EnsureCreated() only creates the schema on a brand-new DB; it won't add
    // tables introduced after the initial deployment. Run these as IF NOT EXISTS
    // so they are safe on both new and existing databases.
    db.Database.ExecuteSqlRaw("""
        CREATE TABLE IF NOT EXISTS "UserCoffees" (
            "Id"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId"   text NOT NULL,
            "CoffeeId" integer NOT NULL,
            "AddedAt"  timestamp with time zone NOT NULL DEFAULT NOW()
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserCoffees_UserId_CoffeeId"
            ON "UserCoffees" ("UserId", "CoffeeId");

        CREATE TABLE IF NOT EXISTS "UserGrinders" (
            "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId"    text NOT NULL,
            "GrinderId" integer NOT NULL,
            "AddedAt"   timestamp with time zone NOT NULL DEFAULT NOW()
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserGrinders_UserId_GrinderId"
            ON "UserGrinders" ("UserId", "GrinderId");

        CREATE TABLE IF NOT EXISTS "UserBrewMethods" (
            "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId"     text NOT NULL,
            "BrewMethod" integer NOT NULL,
            "AddedAt"    timestamp with time zone NOT NULL DEFAULT NOW()
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserBrewMethods_UserId_BrewMethod"
            ON "UserBrewMethods" ("UserId", "BrewMethod");

        CREATE TABLE IF NOT EXISTS "CoffeeBags" (
            "Id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId"      text NOT NULL,
            "CoffeeId"    integer NOT NULL,
            "OpenedAt"    timestamp with time zone NOT NULL DEFAULT NOW(),
            "RoastedOn"   date,
            "BagWeightG"  numeric(6,1),
            "Notes"       text
        );

        CREATE TABLE IF NOT EXISTS "AdminAuditLogs" (
            "Id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ActorId"     text NOT NULL,
            "ActorEmail"  text NOT NULL,
            "Action"      text NOT NULL,
            "EntityType"  text NOT NULL,
            "EntityId"    text,
            "OldValue"    text,
            "NewValue"    text,
            "Notes"       text,
            "IpAddress"   text,
            "Timestamp"   timestamp with time zone NOT NULL DEFAULT NOW()
        );
        """);

    SeedData.Seed(db);

    // ── Seed Admin Role & User ────────────────────────────────────────────────
    var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();
    var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();

    if (!await roleManager.RoleExistsAsync("Admin"))
        await roleManager.CreateAsync(new IdentityRole("Admin"));

    var adminEmail    = app.Configuration["Admin:Email"]    ?? "admin@grindatlas.com";
    var adminPassword = app.Configuration["Admin:Password"] ?? "Admin123!";

    var adminUser = await userManager.FindByEmailAsync(adminEmail);
    if (adminUser is null)
    {
        adminUser = new ApplicationUser
        {
            Email       = adminEmail,
            UserName    = adminEmail,
            DisplayName = "Admin",
        };
        await userManager.CreateAsync(adminUser, adminPassword);
    }

    if (!await userManager.IsInRoleAsync(adminUser, "Admin"))
        await userManager.AddToRoleAsync(adminUser, "Admin");
}

app.UseSwagger();
app.UseSwaggerUI();
app.UseCors();
app.UseAuthentication();
app.UseAuthorization();
app.UseRateLimiter();
app.MapControllers();
app.Run();
